swagger_parser:
  # You must provide the file path and/or url to the OpenApi schema.
  
  # Sets the OpenApi schema path directory for api definition.
  # schema_path: schemas/openapi.json

  # Sets the url of the OpenApi schema.
  schema_url: https://petstore.swagger.io/v2/swagger.json
  
  # Required. Sets output directory for generated files (Clients and DTOs).
  output_directory: lib/api

  # Optional. Sets the programming language.
  # Current available languages are: dart, kotlin.
  language: dart

  # Optional. If 'schema_path' and 'schema_url' are specified, what will be used.
  # Current available options are: path, url.
  prefer_schema_source: url

  # Optional (dart only).
  # Current available serializers are: json_serializable, freezed, dart_mappable.
  json_serializer: json_serializable

  # Optional (dart only). Set 'true' to generate root client
  # with interface and all clients instances.
  root_client: true

  # Optional (dart only). Set root client name.
  root_client_name: RestClient

  # Optional. Set default content-type for all requests.
  default_content_type: "application/json"

  # Optional. Set API name for folder and export file
  # If not specified, the file name is used.
  name: null

  # Optional (dart only). Set 'true' to generate export file.
  export_file: true

  # Optional. Set to 'true' to put the all api in its folder.
  put_in_folder: false

  # Optional. Set 'true' to put all clients in clients folder.
  put_clients_in_folder: false

  # Optional. Set to 'true' to squash all clients in one client.
  squash_clients: false

  # Optional. Set to 'false' to not write the schema from the url to the schema file.
  schema_from_url_to_file: true

  # Optional. Set postfix for Client class and file.
  client_postfix: Client

  # Optional. Set 'true' to use only the endpoint path for the method name.
  # Set 'false' to use operationId
  path_method_name: false

  # Optional (dart only). Set 'true' to include toJson() in enums. 
  # If set to false, serialization will use .name instead.
  enums_to_json: false

  # Optional. Set 'true' to set enum prefix from parent component.
  enums_prefix: false

  # Optional (dart only). Set 'true' to maintain backwards compatibility when adding new values on the backend.
  unknown_enum_value: true

  # Optional. Set 'false' to not put a comment at the beginning of the generated files.
  mark_files_as_generated: true

  # Optional (dart only). Set 'true' to wrap all request return types with HttpResponse.
  original_http_response: false

  # Optional. Set regex replacement rules for the names of the generated classes/enums.
  # All rules are applied in order.
  replacement_rules:
    # Example of rule
    - pattern: "[0-9]+"
      replacement: ""

  # Optional. Skip parameters with names.
  skip_parameters:
    - 'X-Some-Token'